import type { Bot, BotId } from "./types";

const CELEB_NOISE = [
  "singer",
  "actor",
  "actress",
  "celebrity",
  "lawsuit",
  "divorced",
  "dating",
  "arrested for",
  "reality tv",
];

const US_SPORTS_NOISE = [
  "nfl",
  "nba",
  "mlb",
  "nhl",
  "ncaa",
  "super bowl",
  "touchdown",
  "quarterback",
  "basketball",
  "baseball",
  "hockey",
  "cricket",
  "tennis",
  "golf",
  "nascar",
  "formula 1",
  "f1",
  "ufc",
  "mma",
  "boxing",
  "rugby",
  "wnba",
  "march madness",
  "world series",
  "stanley cup",
];

export const BOTS: Bot[] = [
  {
    id: "globie",
    name: "globie",
    handle: "world desk",
    emoji: "🌍",
    topic: "Global",
    color: "#5eb0ff",
    bubble: "#102033",
    tagline: "wars, votes, disasters — that's it",
    vibe: "You're Globie in a group chat. You only text when the world actually shifted. Talk like a sharp friend: casual, dry, a little unhinged, still accurate. Use proper sentence case. Never invent facts.",
    feeds: [
      "https://news.google.com/rss/headlines/section/topic/WORLD?hl=en-US&gl=US&ceid=US:en",
      "https://feeds.bbci.co.uk/news/world/rss.xml",
    ],
    exclude: [...CELEB_NOISE, "tips", "recipe", "horoscope", "how to"],
    boost: [
      "war",
      "ceasefire",
      "earthquake",
      "hurricane",
      "election",
      "president",
      "prime minister",
      "sanctions",
      "coup",
      "invasion",
      "nato",
      "un ",
      "nuclear",
      "treaty",
      "refugees",
      "protest",
      "israel",
      "gaza",
      "ukraine",
      "china",
      "taiwan",
    ],
  },
  {
    id: "sporty",
    name: "sporty",
    handle: "sports desk",
    emoji: "⚽",
    topic: "Sports",
    color: "#4ade80",
    bubble: "#102418",
    tagline: "the sports, leagues, and teams you picked",
    vibe: "You're sporty. You only cover the sports, leagues, and teams this person follows. Text like a group chat after a last-minute winner. Keep facts straight. Don't wander into sports they didn't pick.",
    feeds: [
      "https://feeds.bbci.co.uk/sport/football/rss.xml",
      "https://www.theguardian.com/football/rss",
    ],
    mustInclude: [
      "soccer",
      "fifa",
      "uefa",
      "premier league",
      "la liga",
      "serie a",
      "bundesliga",
      "ligue 1",
      "champions league",
      "europa league",
      "world cup",
      "euros",
      "mls",
      "football club",
      " fc",
      "messi",
      "ronaldo",
      "mbappe",
      "haaland",
      "salah",
      "yamal",
      "real madrid",
      "barcelona",
      "liverpool",
      "arsenal",
      "chelsea",
      "manchester",
      "bayern",
      "psg",
      "tottenham",
      "newcastle",
      "inter milan",
      "juventus",
      "atletico",
      "transfer",
      "hat-trick",
      "hat trick",
      "striker",
      "midfielder",
      "goalkeeper",
      "offside",
      "penalty",
    ],
    exclude: US_SPORTS_NOISE,
    boost: [
      "champions league",
      "premier league",
      "world cup",
      "final",
      "transfer",
      "hat-trick",
      "messi",
      "ronaldo",
      "injured",
      "sacked",
      "manager",
    ],
  },
  {
    id: "techie",
    name: "techie",
    handle: "tech desk",
    emoji: "💻",
    topic: "Tech",
    color: "#67e8f9",
    bubble: "#0c2428",
    tagline: "only if it actually changes the internet",
    vibe: "You're techie. You ignore startup fundraising noise and 'app is down' unless it's huge. Cover AI, big-tech, privacy, major launches. Skeptical. Text like a group chat, not a press release.",
    feeds: [
      "https://news.google.com/rss/headlines/section/topic/TECHNOLOGY?hl=en-US&gl=US&ceid=US:en",
      "https://www.theverge.com/rss/index.xml",
      "https://techcrunch.com/feed/",
    ],
    exclude: ["how to", "deal of the day", "coupon", "best laptops", "review:", "beta", "seeds"],
    boost: [
      "openai",
      "apple",
      "google",
      "microsoft",
      "nvidia",
      "tesla",
      "meta",
      "ai ",
      "antitrust",
      "breach",
      "hack",
      "outage",
      "iphone",
      "android",
      "chip",
      "regulation",
    ],
  },
  {
    id: "popcorn",
    name: "popcorn",
    handle: "culture desk",
    emoji: "🎬",
    topic: "Culture",
    color: "#fbbf24",
    bubble: "#261c0a",
    tagline: "main-character entertainment only",
    vibe: "You're popcorn. Only the real tea: huge releases, awards, chart-breakers, internet-breaking celebrity moments. No random dating rumors. Playful, not mean. Cite the actual news.",
    feeds: [
      "https://news.google.com/rss/headlines/section/topic/ENTERTAINMENT?hl=en-US&gl=US&ceid=US:en",
    ],
    exclude: ["obituary: lesser", "coupon"],
    boost: [
      "oscar",
      "grammy",
      "emmy",
      "box office",
      "netflix",
      "taylor swift",
      "beyonce",
      "album",
      "tour",
      "trailer",
      "marvel",
      "streaming",
    ],
  },
  {
    id: "stonks",
    name: "stonks",
    handle: "markets desk",
    emoji: "📈",
    topic: "Money",
    color: "#34d399",
    bubble: "#0c2218",
    tagline: "fed, crashes, mega layoffs — not random tickers",
    vibe: "You're stonks. Only macro or mega-company news. Never give financial advice. Ironic, not reckless. Make the number make sense in one line.",
    feeds: [
      "https://news.google.com/rss/headlines/section/topic/BUSINESS?hl=en-US&gl=US&ceid=US:en",
      "https://feeds.bbci.co.uk/news/business/rss.xml",
    ],
    exclude: ["coupon", "best credit card", "how to save"],
    boost: [
      "federal reserve",
      "fed ",
      "inflation",
      "recession",
      "interest rate",
      "layoff",
      "ipo",
      "crash",
      "bank",
      "jobs report",
      "unemployment",
      "tariff",
    ],
  },
  {
    id: "labrat",
    name: "labrat",
    handle: "science desk",
    emoji: "🧪",
    topic: "Science",
    color: "#c084fc",
    bubble: "#1c1230",
    tagline: "space, climate, real breakthroughs",
    vibe: "You're labrat. Only real discoveries, NASA, climate, major health science. No diet clickbait. Excited nerd, still honest about uncertainty.",
    feeds: [
      "https://news.google.com/rss/headlines/section/topic/SCIENCE?hl=en-US&gl=US&ceid=US:en",
      "https://www.nasa.gov/feed/",
    ],
    exclude: ["weight loss", "supplement", "horoscope", "zodiac"],
    boost: [
      "nasa",
      "climate",
      "vaccine",
      "cancer",
      "quantum",
      "mars",
      "telescope",
      "breakthrough",
      "peer-reviewed",
      "fda",
    ],
  },
  {
    id: "pitch",
    name: "pitch",
    handle: "live football",
    emoji: "📡",
    topic: "Live football",
    color: "#fb7185",
    bubble: "#2a1216",
    tagline: "live scores, tables, who just scored",
    vibe: "You're Pitch, the live football desk. You watch ESPN scoreboards in real time. When someone asks a score, the table, or kickoff, answer from the LIVE DATA you were given — never invent a score. Text like a friend during a match: short, exact, proper sentence case. If a match isn't on yet, say when it is. If you don't have the number, say so.",
    feeds: [],
  },
];

export const GROUP_CHAT_ID = "group";

export function getBot(id: string): Bot | undefined {
  return BOTS.find((bot) => bot.id === id);
}

export function isBotId(value: string): value is BotId {
  return BOTS.some((bot) => bot.id === value);
}

export function dmChatId(botId: BotId): string {
  return `dm-${botId}`;
}

export function botFromChatId(chatId: string): Bot | undefined {
  if (!chatId.startsWith("dm-")) return undefined;
  return getBot(chatId.slice(3));
}

export function hexAlpha(hex: string, alpha: number) {
  const raw = hex.replace("#", "");
  const full = raw.length === 3 ? raw.split("").map((part) => part + part).join("") : raw;
  const r = Number.parseInt(full.slice(0, 2), 16);
  const g = Number.parseInt(full.slice(2, 4), 16);
  const b = Number.parseInt(full.slice(4, 6), 16);
  if ([r, g, b].some((value) => Number.isNaN(value))) return `rgba(255,255,255,${alpha})`;
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}